language: node_js

install:
- cd extension && npm install && cd ..

env: # important! Without the top-level env, no job will be allowed to fail.
- JOB_DEFAULT=test

matrix:
  fast_finish: true
  include:
  - node_js: 8
    env: TYPE=UNIT_CODESTYLE_DEPENDENCY
    script:
    - cd extension
    - npm run cover
    - npm run lint
    - npm audit
  - node_js: 8
    env: TYPE=INTEGRATION
    script:
    - if [[ "$INTEGRATION_CREDENTIALS" ]]; then echo "${INTEGRATION_CREDENTIALS}" > .integration-credentials.js; fi
    - cd extension
    - if [[ "$INTEGRATION_CREDENTIALS" ]]; then npm run test:integration; fi
  allow_failures:
  - node_js: 8
    env: TYPE=INTEGRATION
